on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      JAVA_HOME: your mom
    steps:
      - name: Hello world action step
        id: hello
        uses: imralav/greet-gh-action@main
        with:
          who-to-greet: 'Mona the Octocat'
          who-not-to-greet: ${{ env.JAVA_HOME }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Who to dislike
        run: echo "Let's dislike ${{ steps.hello.outputs.who-to-dislike }}"
