on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      JAVA_HOME: "c://program files/jdk1.8.0"
    steps:
      - name: Hello world action step
        id: hello
        uses: imralav/greet-gh-action@main
        with:
          who-to-greet: 'Mona the Octocat'
          who-not-to-greet: ${{ env.JAVA_HOME }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Who to dislike
        run: echo "Let's dislike ${{ steps.hello.outputs.who-to-dislike }}"
      - name: checkout
        uses: actions/checkout@v4
      - name: greet again
        run: node ./elo.js
      - name: output something to file
        run: echo "# no siemka znowu" >> greeting.md
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: greeting-file
          path: greeting.md
  hello_otherworld_job:
    runs-on: ubuntu-latest
    needs: hello_world_job
    steps:
      - name: download the greeting
        uses: actions/download-artifact@v4
        with:
          name: greeting-file
      - name: read greeting
        run: cat greeting.md
